// Copyright (c) 2026-present The Bitweb Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <boost/test/unit_test.hpp>

#include <crypto/argon2d/argon2.h>
#include <test/data/argon2id_vectors.json.h>
#include <test/util/json.h>
#include <uint256.h>
#include <util/strencodings.h>

#include <algorithm>
#include <iostream>
#include <vector>

BOOST_AUTO_TEST_SUITE(crypto_argon2id_tests)

/**
 * Positive test: verify that all ISA implementations (STANDARD, SSE2, SSSE3,
 * AVX2, AVX512) produce the exact same 32-byte hash for a set of 500
 * pseudo-random test vectors generated by a Python reference script.
 *
 * The test vectors are stored in `argon2id_vectors.json` (embedded via
 * CMake). Each vector contains:
 *   - "data": hex-encoded input (password)
 *   - "salt": hex-encoded salt
 *   - "expected_hash": hex-encoded Argon2id output (32 bytes) in **big‑endian**
 *
 * Internally `argon2id_hash_raw` returns the hash via a `uint256` object.
 * Bitcoin Core's `uint256` stores the 32 bytes in **little‑endian** order and
 * its `begin()` / `end()` iterators yield that little‑endian representation.
 *
 * To perform a byte‑wise comparison we reverse the expected hash once to
 * little‑endian, and then compare the byte vectors directly. This approach
 * is platform‑independent and does not rely on any endian‑specific helpers.
 */
BOOST_AUTO_TEST_CASE(argon2id_json_vectors_all_isa)
{
    UniValue tests = read_json(json_tests::argon2id_vectors);
    BOOST_REQUIRE(!tests.isNull());
    BOOST_REQUIRE(tests.isArray());
    BOOST_REQUIRE_GT(tests.size(), 0);

    constexpr uint32_t t_cost = 3;
    constexpr uint32_t m_cost = 1024;   // KiB
    constexpr uint32_t parallelism = 1;
    constexpr size_t   hash_len = 32;

    size_t failed_count = 0;

    for (size_t idx = 0; idx < tests.size(); ++idx) {
        const UniValue& vec = tests[idx];
        std::string data_hex = vec["data"].get_str();
        std::string salt_hex = vec["salt"].get_str();
        std::string expected_hex = vec["expected_hash"].get_str();

        std::vector<uint8_t> data = ParseHex(data_hex);
        std::vector<uint8_t> salt = ParseHex(salt_hex);
        std::vector<uint8_t> expected = ParseHex(expected_hex);
        BOOST_REQUIRE(!data.empty());
        BOOST_REQUIRE(!salt.empty());
        BOOST_REQUIRE(expected.size() == hash_len);

        // Reverse expected from big‑endian (as stored in the JSON) to
        // little‑endian, matching the byte order of uint256 iterators.
        std::reverse(expected.begin(), expected.end());

        // Helper lambda to test a specific ISA implementation
        auto check_isa = [&](argon2_implementation::UseImplementation impl,
                             const std::string& name) {
            Argon2AutoDetect(impl);
            uint256 hash;
            int rc = argon2id_hash_raw(t_cost, m_cost, parallelism,
                                       data.data(), data.size(),
                                       salt.data(), salt.size(),
                                       hash.begin(), hash_len);
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                                  name << " failed at vector " << idx);

            std::vector<uint8_t> actual(hash.begin(), hash.end());
            if (actual != expected) {
                ++failed_count;
                // For error reporting, reverse back to big‑endian so the
                // printed hex matches the original JSON.
                std::vector<uint8_t> actual_be = actual;
                std::reverse(actual_be.begin(), actual_be.end());
                std::cerr << "Vector " << idx << " " << name << " mismatch:\n"
                          << "  data: " << data_hex << "\n"
                          << "  salt: " << salt_hex << "\n"
                          << "  expected: " << expected_hex << "\n"
                          << "  actual:   " << HexStr(actual_be) << "\n";
            }
        };

        // Verify all available ISA implementations
        check_isa(argon2_implementation::STANDARD, "STANDARD");
        check_isa(argon2_implementation::USE_SSE2,   "SSE2");
        check_isa(argon2_implementation::USE_SSSE3,  "SSSE3");
        check_isa(argon2_implementation::USE_AVX2,   "AVX2");
        check_isa(argon2_implementation::USE_AVX512, "AVX512");
    }

    // Restore automatic ISA detection for subsequent tests
    Argon2AutoDetect();

    BOOST_REQUIRE_EQUAL(failed_count, 0);
}

/**
 * Negative test: ensure that the byte comparison used in the positive test
 * actually detects a mismatch. We take the first test vector and deliberately
 * corrupt the expected hash, then assert that the computed hash does *not*
 * match the corrupted one.
 *
 * If the positive test were accidentally comparing strings that always return
 * true, this test would fail, catching a false‑positive situation.
 */
BOOST_AUTO_TEST_CASE(argon2id_negative_test)
{
    UniValue tests = read_json(json_tests::argon2id_vectors);
    BOOST_REQUIRE(!tests.isNull());
    BOOST_REQUIRE(tests.isArray());
    BOOST_REQUIRE_GT(tests.size(), 0);

    const UniValue& vec = tests[0];
    std::vector<uint8_t> data = ParseHex(vec["data"].get_str());
    std::vector<uint8_t> salt = ParseHex(vec["salt"].get_str());
    std::vector<uint8_t> expected = ParseHex(vec["expected_hash"].get_str());
    BOOST_REQUIRE(!data.empty() && !salt.empty() && expected.size() == 32);

    // Convert to little‑endian as done in the positive test
    std::reverse(expected.begin(), expected.end());

    // Corrupt the first byte
    expected[0] ^= 0xFF;

    Argon2AutoDetect(argon2_implementation::STANDARD);
    uint256 hash;
    int rc = argon2id_hash_raw(3, 1024, 1,
                               data.data(), data.size(),
                               salt.data(), salt.size(),
                               hash.begin(), 32);
    BOOST_REQUIRE_EQUAL(rc, ARGON2_OK);

    std::vector<uint8_t> actual(hash.begin(), hash.end());
    // They must differ
    BOOST_CHECK(actual != expected);

    Argon2AutoDetect();
}

BOOST_AUTO_TEST_SUITE_END()
