// Copyright (c) 2026-present The Bitweb Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

/**
 * crypto_argon2_api_tests.cpp
 *
 * Tests for the ported Argon2 library against Python-generated test vectors.
 * Covers every public API surface:
 *
 *   argon2[d/i/id]_hash_raw       – typed convenience wrappers, all ISAs
 *   argon2[d/i/id]_hash_encoded   – typed wrappers, exact PHC-string match
 *   argon2[d/i/id]_verify         – typed verify against Python vectors
 *   argon2_hash()                 – generic wrapper, raw and encoded paths
 *   argon2_verify()               – generic verify
 *   argon2_ctx() / argon2[d/i/id]_ctx()        – low-level context API
 *   argon2[d/i/id]_verify_ctx() / argon2_verify_ctx() – context verify
 *   argon2_encodedlen()           – predicted size must match actual
 *   argon2_error_message()        – non-null/non-empty for all known codes
 *
 * Vectors are generated by generate_argon2_api_vectors.py (argon2-cffi).
 */

#include <boost/test/unit_test.hpp>

#include <crypto/argon2d/argon2.h>
#include <test/data/argon2_api_test_vectors.json.h>
#include <univalue.h>
#include <util/strencodings.h>

#include <cstring>
#include <functional>
#include <string>
#include <vector>

BOOST_AUTO_TEST_SUITE(crypto_argon2_api_tests)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static argon2_type ParseArgon2Type(const std::string& s)
{
    if (s == "argon2d")  return Argon2_d;
    if (s == "argon2i")  return Argon2_i;
    if (s == "argon2id") return Argon2_id;
    BOOST_FAIL("Unknown argon2 type: " + s);
    return Argon2_id;
}

static int TypedHashRaw(argon2_type type,
                        uint32_t t, uint32_t m, uint32_t p,
                        const void* pwd, size_t pwdlen,
                        const void* salt, size_t saltlen,
                        void* hash, size_t hashlen)
{
    switch (type) {
    case Argon2_d:  return argon2d_hash_raw (t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    case Argon2_i:  return argon2i_hash_raw (t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    case Argon2_id: return argon2id_hash_raw(t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    }
    return ARGON2_INCORRECT_TYPE;
}

static int TypedHashEncoded(argon2_type type,
                            uint32_t t, uint32_t m, uint32_t p,
                            const void* pwd, size_t pwdlen,
                            const void* salt, size_t saltlen,
                            size_t hashlen, char* enc, size_t enclen)
{
    switch (type) {
    case Argon2_d:  return argon2d_hash_encoded (t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    case Argon2_i:  return argon2i_hash_encoded (t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    case Argon2_id: return argon2id_hash_encoded(t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    }
    return ARGON2_INCORRECT_TYPE;
}

static int TypedVerify(argon2_type type, const char* encoded,
                       const void* pwd, size_t pwdlen)
{
    switch (type) {
    case Argon2_d:  return argon2d_verify (encoded, pwd, pwdlen);
    case Argon2_i:  return argon2i_verify (encoded, pwd, pwdlen);
    case Argon2_id: return argon2id_verify(encoded, pwd, pwdlen);
    }
    return ARGON2_INCORRECT_TYPE;
}

/** Call fn for every ISA variant compiled into this binary. */
static void ForEachISA(
    const std::function<void(argon2_implementation::UseImplementation,
                             const std::string&)>& fn)
{
    fn(argon2_implementation::STANDARD, "STANDARD");
#if defined(ENABLE_ARGON2_SSE2)
    fn(argon2_implementation::USE_SSE2,   "SSE2");
#endif
#if defined(ENABLE_ARGON2_SSSE3)
    fn(argon2_implementation::USE_SSSE3,  "SSSE3");
#endif
#if defined(ENABLE_ARGON2_AVX2)
    fn(argon2_implementation::USE_AVX2,   "AVX2");
#endif
#if defined(ENABLE_ARGON2_AVX512)
    fn(argon2_implementation::USE_AVX512, "AVX512");
#endif
#if defined(ENABLE_ARGON2_NEON)
    fn(argon2_implementation::USE_NEON,   "NEON");
#endif
}

static UniValue LoadVectors()
{
    std::string jsondata{json_tests::argon2_api_test_vectors};
    UniValue root;
    BOOST_REQUIRE_MESSAGE(root.read(jsondata), "Failed to parse argon2_api_test_vectors.json");
    BOOST_REQUIRE_MESSAGE(root.isObject(), "Root must be a JSON object");
    return root;
}

// ---------------------------------------------------------------------------
// Test 1 – _hash_raw: all types × all ISAs vs Python reference vectors
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_raw_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["raw_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    size_t failures = 0;

    for (size_t i = 0; i < vecs.size(); ++i) {
        const UniValue& v    = vecs[i];
        const std::string ts = v["type"].get_str();
        const uint32_t t     = v["t_cost"].getInt<uint32_t>();
        const uint32_t m     = v["m_cost"].getInt<uint32_t>();
        const uint32_t p     = v["parallelism"].getInt<uint32_t>();
        const size_t hlen    = v["hash_len"].getInt<size_t>();
        const auto data      = ParseHex(v["data"].get_str());
        const auto salt      = ParseHex(v["salt"].get_str());
        const auto expected  = ParseHex(v["expected_hash"].get_str());
        const argon2_type type = ParseArgon2Type(ts);

        BOOST_REQUIRE(expected.size() == hlen);

        ForEachISA([&](argon2_implementation::UseImplementation impl,
                       const std::string& isa) {
            Argon2AutoDetect(impl);
            std::vector<uint8_t> out(hlen);
            int rc = TypedHashRaw(type, t, m, p,
                                  data.data(), data.size(),
                                  salt.data(), salt.size(),
                                  out.data(), hlen);
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                isa << " hash_raw rc=" << rc << " vec=" << i << " type=" << ts);
            if (out != expected) {
                ++failures;
                BOOST_TEST_MESSAGE("MISMATCH hash_raw vec=" << i
                    << " type=" << ts << " isa=" << isa
                    << " expected=" << v["expected_hash"].get_str()
                    << " actual="   << HexStr(out));
            }
        });
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 2 – _hash_encoded: exact PHC-string match vs Python reference vectors
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_encoded_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["encoded_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (size_t i = 0; i < vecs.size(); ++i) {
        const UniValue& v    = vecs[i];
        const std::string ts = v["type"].get_str();
        const uint32_t t     = v["t_cost"].getInt<uint32_t>();
        const uint32_t m     = v["m_cost"].getInt<uint32_t>();
        const uint32_t p     = v["parallelism"].getInt<uint32_t>();
        const size_t hlen    = v["hash_len"].getInt<size_t>();
        const auto data      = ParseHex(v["data"].get_str());
        const auto salt      = ParseHex(v["salt"].get_str());
        const std::string py_enc = v["encoded"].get_str();
        const argon2_type type   = ParseArgon2Type(ts);

        size_t enc_len = argon2_encodedlen(t, m, p,
                                           static_cast<uint32_t>(salt.size()),
                                           static_cast<uint32_t>(hlen), type);
        BOOST_REQUIRE_GT(enc_len, 0);
        std::vector<char> buf(enc_len);

        int rc = TypedHashEncoded(type, t, m, p,
                                  data.data(), data.size(),
                                  salt.data(), salt.size(),
                                  hlen, buf.data(), enc_len);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "hash_encoded rc=" << rc << " vec=" << i << " type=" << ts);

        const std::string enc(buf.data());
        BOOST_CHECK_MESSAGE(enc == py_enc,
            "Encoded mismatch vec=" << i << " type=" << ts
            << "\n  cpp: " << enc
            << "\n  py:  " << py_enc);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 3 – _verify: Python-generated encoded strings must verify correctly
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_verify_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["encoded_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);
    size_t failures = 0;

    for (size_t i = 0; i < vecs.size(); ++i) {
        const UniValue& v       = vecs[i];
        const std::string ts    = v["type"].get_str();
        const auto data         = ParseHex(v["data"].get_str());
        const std::string enc   = v["encoded"].get_str();
        const argon2_type type  = ParseArgon2Type(ts);

        // Correct data → must verify
        int rc = TypedVerify(type, enc.c_str(), data.data(), data.size());
        if (rc != ARGON2_OK) {
            ++failures;
            BOOST_TEST_MESSAGE("VERIFY FAIL vec=" << i << " type=" << ts
                << " rc=" << rc << " encoded=" << enc);
        }

        // Corrupted data → must not verify
        std::vector<uint8_t> corrupt = data;
        corrupt[0] ^= 0xFF;
        BOOST_CHECK_NE(TypedVerify(type, enc.c_str(), corrupt.data(), corrupt.size()),
                       ARGON2_OK);
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 4 – argon2_hash(): generic raw path, all types × all ISAs
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_generic_hash_raw_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["generic_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    size_t failures = 0;

    ForEachISA([&](argon2_implementation::UseImplementation impl,
                   const std::string& isa) {
        Argon2AutoDetect(impl);
        for (size_t i = 0; i < vecs.size(); ++i) {
            const UniValue& v    = vecs[i];
            const std::string ts = v["type"].get_str();
            const uint32_t t     = v["t_cost"].getInt<uint32_t>();
            const uint32_t m     = v["m_cost"].getInt<uint32_t>();
            const uint32_t p     = v["parallelism"].getInt<uint32_t>();
            const size_t hlen    = v["hash_len"].getInt<size_t>();
            const auto data      = ParseHex(v["data"].get_str());
            const auto salt      = ParseHex(v["salt"].get_str());
            const auto expected  = ParseHex(v["expected_hash"].get_str());
            const argon2_type type = ParseArgon2Type(ts);

            std::vector<uint8_t> out(hlen);
            int rc = argon2_hash(t, m, p,
                                 data.data(), data.size(),
                                 salt.data(), salt.size(),
                                 out.data(), hlen,
                                 nullptr, 0,
                                 type, ARGON2_VERSION_NUMBER);
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                isa << " argon2_hash(raw) rc=" << rc << " vec=" << i);
            if (out != expected) {
                ++failures;
                BOOST_TEST_MESSAGE("MISMATCH argon2_hash(raw) vec=" << i
                    << " type=" << ts << " isa=" << isa);
            }
        }
    });

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 5 – argon2_hash(): generic encoded path + argon2_verify()
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_generic_hash_encoded_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["generic_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (size_t i = 0; i < vecs.size(); ++i) {
        const UniValue& v       = vecs[i];
        const std::string ts    = v["type"].get_str();
        const uint32_t t        = v["t_cost"].getInt<uint32_t>();
        const uint32_t m        = v["m_cost"].getInt<uint32_t>();
        const uint32_t p        = v["parallelism"].getInt<uint32_t>();
        const size_t hlen       = v["hash_len"].getInt<size_t>();
        const auto data         = ParseHex(v["data"].get_str());
        const auto salt         = ParseHex(v["salt"].get_str());
        const std::string py_enc = v["encoded"].get_str();
        const argon2_type type   = ParseArgon2Type(ts);

        size_t enc_len = argon2_encodedlen(t, m, p,
                                           static_cast<uint32_t>(salt.size()),
                                           static_cast<uint32_t>(hlen), type);
        std::vector<char> enc_buf(enc_len);
        std::vector<uint8_t> raw_out(hlen);

        int rc = argon2_hash(t, m, p,
                             data.data(), data.size(),
                             salt.data(), salt.size(),
                             raw_out.data(), hlen,
                             enc_buf.data(), enc_len,
                             type, ARGON2_VERSION_NUMBER);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "argon2_hash(encoded) rc=" << rc << " vec=" << i);

        const std::string enc(enc_buf.data());
        BOOST_CHECK_MESSAGE(enc == py_enc,
            "Generic encoded mismatch vec=" << i << " type=" << ts
            << "\n  cpp: " << enc << "\n  py:  " << py_enc);

        // argon2_verify() with correct data
        BOOST_CHECK_MESSAGE(
            argon2_verify(enc_buf.data(), data.data(), data.size(), type) == ARGON2_OK,
            "argon2_verify failed vec=" << i << " type=" << ts);

        // argon2_verify() with wrong type must fail
        const argon2_type other = (type == Argon2_id) ? Argon2_i : Argon2_id;
        BOOST_CHECK_NE(argon2_verify(enc_buf.data(), data.data(), data.size(), other),
                       ARGON2_OK);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 6 – argon2_ctx() / argon2[d/i/id]_ctx(): output must match raw vectors
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_ctx_vectors)
{
    UniValue root = LoadVectors();
    const UniValue& vecs = root["raw_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);
    size_t failures = 0;

    for (size_t i = 0; i < vecs.size(); ++i) {
        const UniValue& v      = vecs[i];
        const std::string ts   = v["type"].get_str();
        const uint32_t t       = v["t_cost"].getInt<uint32_t>();
        const uint32_t m       = v["m_cost"].getInt<uint32_t>();
        const uint32_t p       = v["parallelism"].getInt<uint32_t>();
        const size_t hlen      = v["hash_len"].getInt<size_t>();
        auto data              = ParseHex(v["data"].get_str());
        auto salt              = ParseHex(v["salt"].get_str());
        const auto expected    = ParseHex(v["expected_hash"].get_str());
        const argon2_type type = ParseArgon2Type(ts);

        auto run = [&](bool generic) -> bool {
            std::vector<uint8_t> out(hlen, 0);
            argon2_context ctx;
            std::memset(&ctx, 0, sizeof(ctx));
            ctx.out      = out.data();
            ctx.outlen   = static_cast<uint32_t>(hlen);
            ctx.pwd      = data.data();
            ctx.pwdlen   = static_cast<uint32_t>(data.size());
            ctx.salt     = salt.data();
            ctx.saltlen  = static_cast<uint32_t>(salt.size());
            ctx.t_cost   = t;
            ctx.m_cost   = m;
            ctx.lanes    = p;
            ctx.threads  = p;
            ctx.version  = ARGON2_VERSION_NUMBER;
            ctx.flags    = ARGON2_DEFAULT_FLAGS;

            int rc;
            if (generic) {
                rc = argon2_ctx(&ctx, type);
            } else {
                switch (type) {
                case Argon2_d:  rc = argon2d_ctx(&ctx);  break;
                case Argon2_i:  rc = argon2i_ctx(&ctx);  break;
                case Argon2_id: rc = argon2id_ctx(&ctx); break;
                default:        rc = ARGON2_INCORRECT_TYPE;
                }
            }
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                (generic ? "argon2_ctx" : "typed ctx") << " rc=" << rc << " vec=" << i);
            return out == expected;
        };

        if (!run(false)) { ++failures; BOOST_TEST_MESSAGE("CTX MISMATCH (typed)   vec=" << i << " type=" << ts); }
        if (!run(true))  { ++failures; BOOST_TEST_MESSAGE("CTX MISMATCH (generic) vec=" << i << " type=" << ts); }
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 7 – argon2[d/i/id]_verify_ctx() and argon2_verify_ctx()
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_verify_ctx_api)
{
    const uint8_t pwd[]  = "hunter2";
    const uint8_t salt[] = "saltsalt";
    const size_t pwdlen  = sizeof(pwd)  - 1;
    const size_t saltlen = sizeof(salt) - 1;
    constexpr size_t hlen = 32;

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (argon2_type type : {Argon2_d, Argon2_i, Argon2_id}) {
        std::vector<uint8_t> ref(hlen);
        BOOST_REQUIRE_EQUAL(
            TypedHashRaw(type, 1, 64, 1, pwd, pwdlen, salt, saltlen, ref.data(), hlen),
            ARGON2_OK);

        std::vector<uint8_t> out(hlen), pwd_buf(pwd, pwd + pwdlen), salt_buf(salt, salt + saltlen);
        argon2_context ctx;
        std::memset(&ctx, 0, sizeof(ctx));
        ctx.out     = out.data();  ctx.outlen  = static_cast<uint32_t>(hlen);
        ctx.pwd     = pwd_buf.data();  ctx.pwdlen  = static_cast<uint32_t>(pwdlen);
        ctx.salt    = salt_buf.data(); ctx.saltlen = static_cast<uint32_t>(saltlen);
        ctx.t_cost  = 1; ctx.m_cost = 64; ctx.lanes = 1; ctx.threads = 1;
        ctx.version = ARGON2_VERSION_NUMBER; ctx.flags = ARGON2_DEFAULT_FLAGS;

        int rc;
        switch (type) {
        case Argon2_d:  rc = argon2d_verify_ctx (&ctx, (const char*)ref.data()); break;
        case Argon2_i:  rc = argon2i_verify_ctx (&ctx, (const char*)ref.data()); break;
        case Argon2_id: rc = argon2id_verify_ctx(&ctx, (const char*)ref.data()); break;
        default:        rc = ARGON2_INCORRECT_TYPE;
        }
        BOOST_CHECK_MESSAGE(rc == ARGON2_OK,
            "verify_ctx should succeed for type=" << (int)type);

        BOOST_CHECK_MESSAGE(
            argon2_verify_ctx(&ctx, (const char*)ref.data(), type) == ARGON2_OK,
            "argon2_verify_ctx (generic) should succeed for type=" << (int)type);

        // Corrupted hash → mismatch
        std::vector<uint8_t> bad = ref;
        bad[0] ^= 0xFF;
        switch (type) {
        case Argon2_d:  rc = argon2d_verify_ctx (&ctx, (const char*)bad.data()); break;
        case Argon2_i:  rc = argon2i_verify_ctx (&ctx, (const char*)bad.data()); break;
        case Argon2_id: rc = argon2id_verify_ctx(&ctx, (const char*)bad.data()); break;
        default:        rc = ARGON2_INCORRECT_TYPE;
        }
        BOOST_CHECK_NE(rc, ARGON2_OK);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 8 – argon2_encodedlen(): predicted size must equal strlen(result) + 1
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_encodedlen_utility)
{
    struct Case { argon2_type type; uint32_t t, m, p, saltlen, hashlen; };
    const Case cases[] = {
        {Argon2_d,  1,  64, 1,  8, 16},
        {Argon2_i,  2, 128, 1,  8, 32},
        {Argon2_id, 3, 256, 1, 16, 32},
        {Argon2_id, 1,  64, 4, 32, 32},
        {Argon2_i,  1,  64, 1, 64, 64},
        {Argon2_d,  1, 128, 2, 16, 32},
        {Argon2_id, 1,  64, 1,  8, 64},
    };
    const std::vector<uint8_t> pwd(16, 0xAB);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (const auto& c : cases) {
        const std::vector<uint8_t> salt(c.saltlen, 0xCD);
        size_t enc_len = argon2_encodedlen(c.t, c.m, c.p, c.saltlen, c.hashlen, c.type);
        BOOST_REQUIRE_GT(enc_len, 0);

        std::vector<char> buf(enc_len);
        int rc = TypedHashEncoded(c.type, c.t, c.m, c.p,
                                  pwd.data(), pwd.size(),
                                  salt.data(), salt.size(),
                                  c.hashlen, buf.data(), enc_len);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "hash_encoded rc=" << rc << " type=" << (int)c.type);

        size_t actual = std::strlen(buf.data()) + 1;
        BOOST_CHECK_MESSAGE(actual == enc_len,
            "encodedlen mismatch: predicted=" << enc_len
            << " actual=" << actual << " type=" << (int)c.type);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 9 – argon2_error_message(): non-null, non-empty for every known code
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_error_message_api)
{
    const int codes[] = {
        ARGON2_OK,
        ARGON2_OUTPUT_PTR_NULL,    ARGON2_OUTPUT_TOO_SHORT,    ARGON2_OUTPUT_TOO_LONG,
        ARGON2_PWD_TOO_LONG,       ARGON2_SALT_TOO_SHORT,      ARGON2_SALT_TOO_LONG,
        ARGON2_AD_TOO_LONG,        ARGON2_SECRET_TOO_LONG,     ARGON2_TIME_TOO_SMALL,
        ARGON2_TIME_TOO_LARGE,     ARGON2_MEMORY_TOO_LITTLE,   ARGON2_MEMORY_TOO_MUCH,
        ARGON2_LANES_TOO_FEW,      ARGON2_LANES_TOO_MANY,      ARGON2_PWD_PTR_MISMATCH,
        ARGON2_SALT_PTR_MISMATCH,  ARGON2_SECRET_PTR_MISMATCH, ARGON2_AD_PTR_MISMATCH,
        ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_FREE_MEMORY_CBK_NULL,
        ARGON2_ALLOCATE_MEMORY_CBK_NULL, ARGON2_INCORRECT_PARAMETER,
        ARGON2_INCORRECT_TYPE,     ARGON2_OUT_PTR_MISMATCH,    ARGON2_THREADS_TOO_FEW,
        ARGON2_THREADS_TOO_MANY,   ARGON2_MISSING_ARGS,        ARGON2_ENCODING_FAIL,
        ARGON2_DECODING_FAIL,      ARGON2_THREAD_FAIL,         ARGON2_DECODING_LENGTH_FAIL,
        ARGON2_VERIFY_MISMATCH,
    };
    for (int code : codes) {
        const char* msg = argon2_error_message(code);
        BOOST_CHECK_MESSAGE(msg != nullptr,
            "argon2_error_message returned nullptr for code=" << code);
        if (msg) {
            BOOST_CHECK_MESSAGE(std::strlen(msg) > 0,
                "argon2_error_message returned empty string for code=" << code);
        }
    }
}

// ---------------------------------------------------------------------------
// Test 10 – Invalid parameter handling: expected specific error codes
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_invalid_params)
{
    const uint8_t pwd[]  = "password";
    const uint8_t salt[] = "saltsalt";
    const size_t pwdlen  = sizeof(pwd)  - 1;
    const size_t saltlen = sizeof(salt) - 1;
    uint8_t out[32] = {};

    // t_cost = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);
    // m_cost = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 0, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_MEMORY_TOO_LITTLE);
    // parallelism = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 0, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_LANES_TOO_FEW);
    // salt too short
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 1, pwd, pwdlen, salt, saltlen - 1, out, 32),
        ARGON2_SALT_TOO_SHORT);
    // hash_len = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 1, pwd, pwdlen, salt, saltlen, out, 0),
        ARGON2_OUTPUT_TOO_SHORT);

    // Same checks for the other two types
    BOOST_CHECK_EQUAL(
        argon2d_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);
    BOOST_CHECK_EQUAL(
        argon2i_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);

    // Encoded buffer too small
    char tiny[4] = "";
    BOOST_CHECK_EQUAL(
        argon2id_hash_encoded(1, 64, 1, pwd, pwdlen, salt, saltlen, 32, tiny, sizeof(tiny)),
        ARGON2_ENCODING_FAIL);

    // Garbage encoded string
    BOOST_CHECK_NE(argon2id_verify("not-a-valid-argon2-hash", pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2i_verify ("not-a-valid-argon2-hash", pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2d_verify ("not-a-valid-argon2-hash", pwd, pwdlen), ARGON2_OK);

    // Valid argon2id string rejected by argon2i/argon2d verify
    size_t enc_len = argon2_encodedlen(1, 64, 1,
                                       static_cast<uint32_t>(saltlen), 32, Argon2_id);
    std::vector<char> enc_buf(enc_len);
    BOOST_REQUIRE_EQUAL(
        argon2id_hash_encoded(1, 64, 1, pwd, pwdlen, salt, saltlen, 32,
                              enc_buf.data(), enc_len),
        ARGON2_OK);
    BOOST_CHECK_NE(argon2i_verify(enc_buf.data(), pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2d_verify(enc_buf.data(), pwd, pwdlen), ARGON2_OK);
}

BOOST_AUTO_TEST_SUITE_END()
