// Copyright (c) 2026-present The Bitweb Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

/**
 * crypto_argon2_api_tests.cpp
 *
 * Full-coverage tests for the ported Argon2 library (all three variants:
 * argon2d, argon2i, argon2id) and every public API surface:
 *
 *   _hash_raw         – all three type-specific convenience wrappers
 *   _hash_encoded     – all three type-specific wrappers
 *   _verify           – all three type-specific wrappers
 *   argon2_hash()     – generic function, raw-only and encoded-only paths
 *   argon2_verify()   – generic verify
 *   argon2_ctx()      – low-level context API, generic
 *   argon2[d/i/id]_ctx()         – type-specific context wrappers
 *   argon2[d/i/id]_verify_ctx()  – type-specific context verify
 *   argon2_encodedlen()           – utility: returned size must match actual
 *   argon2_error_message()        – non-null/non-empty for all known codes
 *
 * ISA variants (STANDARD, SSE2, SSSE3, AVX2, AVX512, NEON where compiled in)
 * are exercised by all tests that involve raw hash computation.
 *
 * This is a pure library test — it is NOT a consensus test.
 * Vectors are generated by generate_argon2_api_vectors.py using the
 * reference argon2-cffi Python bindings (libargon2).
 */

#include <boost/test/unit_test.hpp>

#include <crypto/argon2d/argon2.h>
#include <test/data/argon2_api_test_vectors.json.h>
#include <test/util/json.h>
#include <util/strencodings.h>

#include <algorithm>
#include <cstring>
#include <functional>
#include <iostream>
#include <string>
#include <vector>

BOOST_AUTO_TEST_SUITE(crypto_argon2_api_tests)

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Map the JSON "type" string to the argon2_type enum. */
static argon2_type ParseArgon2Type(const std::string& s)
{
    if (s == "argon2d")  return Argon2_d;
    if (s == "argon2i")  return Argon2_i;
    if (s == "argon2id") return Argon2_id;
    BOOST_FAIL("Unknown argon2 type string: " + s);
    return Argon2_id; // unreachable
}

/** Dispatch to the correct typed _hash_raw wrapper. */
static int TypedHashRaw(argon2_type type,
                         uint32_t t, uint32_t m, uint32_t p,
                         const void* pwd, size_t pwdlen,
                         const void* salt, size_t saltlen,
                         void* hash, size_t hashlen)
{
    switch (type) {
    case Argon2_d:  return argon2d_hash_raw(t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    case Argon2_i:  return argon2i_hash_raw(t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    case Argon2_id: return argon2id_hash_raw(t, m, p, pwd, pwdlen, salt, saltlen, hash, hashlen);
    }
    return ARGON2_INCORRECT_TYPE;
}

/** Dispatch to the correct typed _hash_encoded wrapper. */
static int TypedHashEncoded(argon2_type type,
                             uint32_t t, uint32_t m, uint32_t p,
                             const void* pwd, size_t pwdlen,
                             const void* salt, size_t saltlen,
                             size_t hashlen, char* enc, size_t enclen)
{
    switch (type) {
    case Argon2_d:  return argon2d_hash_encoded(t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    case Argon2_i:  return argon2i_hash_encoded(t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    case Argon2_id: return argon2id_hash_encoded(t, m, p, pwd, pwdlen, salt, saltlen, hashlen, enc, enclen);
    }
    return ARGON2_INCORRECT_TYPE;
}

/** Dispatch to the correct typed _verify wrapper. */
static int TypedVerify(argon2_type type,
                        const char* encoded,
                        const void* pwd, size_t pwdlen)
{
    switch (type) {
    case Argon2_d:  return argon2d_verify(encoded, pwd, pwdlen);
    case Argon2_i:  return argon2i_verify(encoded, pwd, pwdlen);
    case Argon2_id: return argon2id_verify(encoded, pwd, pwdlen);
    }
    return ARGON2_INCORRECT_TYPE;
}

/** Expected PHC-string prefix for a given type. */
static std::string TypePrefix(argon2_type type)
{
    switch (type) {
    case Argon2_d:  return "$argon2d$";
    case Argon2_i:  return "$argon2i$";
    case Argon2_id: return "$argon2id$";
    }
    return "";
}

/**
 * Invoke `fn` once for each ISA variant that was compiled into this binary.
 * STANDARD is always included; SIMD variants are gated by their compile-time
 * defines (same macros forwarded from the library CMakeLists).
 */
static void ForEachISA(
    const std::function<void(argon2_implementation::UseImplementation,
                             const std::string&)>& fn)
{
    fn(argon2_implementation::STANDARD, "STANDARD");
#if defined(ENABLE_ARGON2_SSE2)
    fn(argon2_implementation::USE_SSE2,   "SSE2");
#endif
#if defined(ENABLE_ARGON2_SSSE3)
    fn(argon2_implementation::USE_SSSE3,  "SSSE3");
#endif
#if defined(ENABLE_ARGON2_AVX2)
    fn(argon2_implementation::USE_AVX2,   "AVX2");
#endif
#if defined(ENABLE_ARGON2_AVX512)
    fn(argon2_implementation::USE_AVX512, "AVX512");
#endif
#if defined(ENABLE_ARGON2_NEON)
    fn(argon2_implementation::USE_NEON,   "NEON");
#endif
}

// ---------------------------------------------------------------------------
// Test 1 – _hash_raw: all types × all ISAs against Python reference vectors
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_raw_all_types_all_isa)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["raw_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    size_t failures = 0;

    for (size_t idx = 0; idx < vecs.size(); ++idx) {
        const UniValue& v        = vecs[idx];
        const std::string type_s = v["type"].get_str();
        const uint32_t t         = v["t_cost"].getInt<uint32_t>();
        const uint32_t m         = v["m_cost"].getInt<uint32_t>();
        const uint32_t p         = v["parallelism"].getInt<uint32_t>();
        const size_t hlen        = v["hash_len"].getInt<size_t>();
        const auto data          = ParseHex(v["data"].get_str());
        const auto salt          = ParseHex(v["salt"].get_str());
        const auto expected      = ParseHex(v["expected_hash"].get_str());
        const argon2_type type   = ParseArgon2Type(type_s);

        BOOST_REQUIRE(!data.empty());
        BOOST_REQUIRE(!salt.empty());
        BOOST_REQUIRE(expected.size() == hlen);

        ForEachISA([&](argon2_implementation::UseImplementation impl,
                       const std::string& isa_name) {
            Argon2AutoDetect(impl);
            std::vector<uint8_t> out(hlen);
            int rc = TypedHashRaw(type, t, m, p,
                                   data.data(), data.size(),
                                   salt.data(), salt.size(),
                                   out.data(), hlen);
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                isa_name << " hash_raw rc=" << rc
                         << " (vec=" << idx << " type=" << type_s << ")");
            if (out != expected) {
                ++failures;
                std::cerr
                    << "MISMATCH hash_raw vec=" << idx
                    << " type=" << type_s << " isa=" << isa_name
                    << " t=" << t << " m=" << m << " p=" << p
                    << " hlen=" << hlen << "\n"
                    << "  data:     " << v["data"].get_str() << "\n"
                    << "  salt:     " << v["salt"].get_str() << "\n"
                    << "  expected: " << v["expected_hash"].get_str() << "\n"
                    << "  actual:   " << HexStr(out) << "\n";
            }
        });
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 2 – _hash_encoded: format validation (prefix, v=19, m/t/p params)
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_encoded_format_check)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["encoded_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    // Encoded output is deterministic given the inputs, ISA doesn't matter.
    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (size_t idx = 0; idx < vecs.size(); ++idx) {
        const UniValue& v      = vecs[idx];
        const std::string ts   = v["type"].get_str();
        const uint32_t t       = v["t_cost"].getInt<uint32_t>();
        const uint32_t m       = v["m_cost"].getInt<uint32_t>();
        const uint32_t p       = v["parallelism"].getInt<uint32_t>();
        const size_t hlen      = v["hash_len"].getInt<size_t>();
        const auto data        = ParseHex(v["data"].get_str());
        const auto salt        = ParseHex(v["salt"].get_str());
        const argon2_type type = ParseArgon2Type(ts);

        // Let argon2_encodedlen determine the required buffer size
        size_t enc_len = argon2_encodedlen(t, m, p,
                                            static_cast<uint32_t>(salt.size()),
                                            static_cast<uint32_t>(hlen),
                                            type);
        BOOST_REQUIRE_GT(enc_len, 0);
        std::vector<char> enc_buf(enc_len);

        int rc = TypedHashEncoded(type, t, m, p,
                                   data.data(), data.size(),
                                   salt.data(), salt.size(),
                                   hlen, enc_buf.data(), enc_len);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "hash_encoded rc=" << rc << " vec=" << idx << " type=" << ts);

        const std::string enc(enc_buf.data());

        // 1. Must start with the correct type identifier
        const std::string prefix = TypePrefix(type);
        BOOST_CHECK_MESSAGE(enc.rfind(prefix, 0) == 0,
            "Wrong prefix at vec=" << idx << " type=" << ts
            << " got='" << enc.substr(0, prefix.size() + 2) << "'");

        // 2. Must embed the version
        BOOST_CHECK_MESSAGE(enc.find("v=19") != std::string::npos,
            "Missing 'v=19' at vec=" << idx);

        // 3. Must embed all three cost parameters
        BOOST_CHECK_MESSAGE(enc.find("m=" + std::to_string(m)) != std::string::npos,
            "Missing m_cost at vec=" << idx);
        BOOST_CHECK_MESSAGE(enc.find("t=" + std::to_string(t)) != std::string::npos,
            "Missing t_cost at vec=" << idx);
        BOOST_CHECK_MESSAGE(enc.find("p=" + std::to_string(p)) != std::string::npos,
            "Missing parallelism at vec=" << idx);

        // 4. Must match the Python-generated encoded string exactly
        const std::string py_enc = v["encoded"].get_str();
        BOOST_CHECK_MESSAGE(enc == py_enc,
            "Encoded mismatch vec=" << idx << " type=" << ts
            << "\n  cpp: " << enc
            << "\n  py:  " << py_enc);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 3 – _verify: Python-generated encoded strings must pass verification
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_verify_python_encoded_vectors)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["encoded_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);
    size_t failures = 0;

    for (size_t idx = 0; idx < vecs.size(); ++idx) {
        const UniValue& v       = vecs[idx];
        const std::string ts    = v["type"].get_str();
        const auto data         = ParseHex(v["data"].get_str());
        const std::string enc   = v["encoded"].get_str();
        const argon2_type type  = ParseArgon2Type(ts);

        int rc = TypedVerify(type, enc.c_str(), data.data(), data.size());
        if (rc != ARGON2_OK) {
            ++failures;
            std::cerr << "VERIFY FAIL vec=" << idx << " type=" << ts
                      << " rc=" << rc << "\n  encoded=" << enc << "\n";
        }
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 4 – hash_encoded → verify roundtrip (fully in C++, no JSON dependency)
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_verify_roundtrip)
{
    struct Case { argon2_type type; uint32_t t, m, p; size_t hlen; };
    const Case cases[] = {
        {Argon2_d,  1,  64, 1, 32},
        {Argon2_i,  2, 128, 1, 32},
        {Argon2_id, 1,  64, 1, 32},
        {Argon2_d,  1,  64, 1, 16},
        {Argon2_i,  1,  64, 1, 64},
        {Argon2_id, 1,  64, 4, 32},
        {Argon2_d,  3, 256, 1, 32},
        {Argon2_i,  1, 128, 2, 32},
        {Argon2_id, 2,  64, 1, 64},
    };

    const uint8_t pwd[]     = "correct horse battery staple";
    const size_t  pwdlen    = sizeof(pwd) - 1;
    const uint8_t wrong_pwd[] = "Correct Horse Battery Staple";  // capital letters
    const uint8_t salt[]    = "NaCl is a mineral";
    const size_t  saltlen   = sizeof(salt) - 1;

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (const auto& c : cases) {
        size_t enc_len = argon2_encodedlen(c.t, c.m, c.p,
                                            static_cast<uint32_t>(saltlen),
                                            static_cast<uint32_t>(c.hlen),
                                            c.type);
        std::vector<char> enc_buf(enc_len);
        int rc = TypedHashEncoded(c.type, c.t, c.m, c.p,
                                   pwd, pwdlen, salt, saltlen,
                                   c.hlen, enc_buf.data(), enc_len);
        BOOST_REQUIRE_EQUAL(rc, ARGON2_OK);

        // Correct password → ARGON2_OK
        rc = TypedVerify(c.type, enc_buf.data(), pwd, pwdlen);
        BOOST_CHECK_MESSAGE(rc == ARGON2_OK,
            "verify failed for correct pwd, type=" << (int)c.type);

        // Wrong password → ARGON2_VERIFY_MISMATCH
        rc = TypedVerify(c.type, enc_buf.data(), wrong_pwd, sizeof(wrong_pwd) - 1);
        BOOST_CHECK_MESSAGE(rc == ARGON2_VERIFY_MISMATCH,
            "verify unexpectedly succeeded for wrong pwd, type=" << (int)c.type);

        // Wrong type → should not verify (type is embedded in the string)
        const argon2_type other = (c.type == Argon2_id) ? Argon2_i : Argon2_id;
        rc = TypedVerify(other, enc_buf.data(), pwd, pwdlen);
        BOOST_CHECK_NE(rc, ARGON2_OK);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 5 – argon2_hash() generic: raw-output path, all types × all ISAs
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_generic_hash_raw)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["generic_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    size_t failures = 0;

    ForEachISA([&](argon2_implementation::UseImplementation impl,
                   const std::string& isa_name) {
        Argon2AutoDetect(impl);
        for (size_t idx = 0; idx < vecs.size(); ++idx) {
            const UniValue& v      = vecs[idx];
            const std::string ts   = v["type"].get_str();
            const uint32_t t       = v["t_cost"].getInt<uint32_t>();
            const uint32_t m       = v["m_cost"].getInt<uint32_t>();
            const uint32_t p       = v["parallelism"].getInt<uint32_t>();
            const size_t hlen      = v["hash_len"].getInt<size_t>();
            const auto data        = ParseHex(v["data"].get_str());
            const auto salt        = ParseHex(v["salt"].get_str());
            const auto expected    = ParseHex(v["expected_hash"].get_str());
            const argon2_type type = ParseArgon2Type(ts);

            std::vector<uint8_t> out(hlen);
            // Pass nullptr/0 for the encoded path — raw only
            int rc = argon2_hash(t, m, p,
                                  data.data(), data.size(),
                                  salt.data(), salt.size(),
                                  out.data(), hlen,
                                  /*encoded=*/nullptr, /*encodedlen=*/0,
                                  type, ARGON2_VERSION_NUMBER);
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                isa_name << " argon2_hash(raw) rc=" << rc
                         << " vec=" << idx << " type=" << ts);
            if (out != expected) {
                ++failures;
                std::cerr << "MISMATCH argon2_hash(raw) vec=" << idx
                          << " type=" << ts << " isa=" << isa_name << "\n";
            }
        }
    });

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 6 – argon2_hash() generic: encoded-output path + argon2_verify()
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_generic_hash_encoded_and_verify)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["generic_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (size_t idx = 0; idx < vecs.size(); ++idx) {
        const UniValue& v      = vecs[idx];
        const std::string ts   = v["type"].get_str();
        const uint32_t t       = v["t_cost"].getInt<uint32_t>();
        const uint32_t m       = v["m_cost"].getInt<uint32_t>();
        const uint32_t p       = v["parallelism"].getInt<uint32_t>();
        const size_t hlen      = v["hash_len"].getInt<size_t>();
        const auto data        = ParseHex(v["data"].get_str());
        const auto salt        = ParseHex(v["salt"].get_str());
        const std::string py_enc = v["encoded"].get_str();
        const argon2_type type = ParseArgon2Type(ts);

        size_t enc_len = argon2_encodedlen(t, m, p,
                                            static_cast<uint32_t>(salt.size()),
                                            static_cast<uint32_t>(hlen), type);
        std::vector<char> enc_buf(enc_len);

        // Encoded-only output: pass nullptr for the raw hash buffer
        int rc = argon2_hash(t, m, p,
                              data.data(), data.size(),
                              salt.data(), salt.size(),
                              /*hash=*/nullptr, /*hashlen=*/0,
                              enc_buf.data(), enc_len,
                              type, ARGON2_VERSION_NUMBER);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "argon2_hash(encoded) rc=" << rc << " vec=" << idx);

        const std::string cpp_enc(enc_buf.data());

        // Must match Python reference exactly
        BOOST_CHECK_MESSAGE(cpp_enc == py_enc,
            "Generic encoded mismatch vec=" << idx << " type=" << ts
            << "\n  cpp: " << cpp_enc
            << "\n  py:  " << py_enc);

        // argon2_verify() with correct data → OK
        rc = argon2_verify(enc_buf.data(), data.data(), data.size(), type);
        BOOST_CHECK_MESSAGE(rc == ARGON2_OK,
            "argon2_verify failed vec=" << idx << " type=" << ts);

        // argon2_verify() with wrong type must not succeed
        const argon2_type other = (type == Argon2_id) ? Argon2_i : Argon2_id;
        rc = argon2_verify(enc_buf.data(), data.data(), data.size(), other);
        BOOST_CHECK_NE(rc, ARGON2_OK);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 7 – argon2[d/i/id]_ctx() and argon2_ctx(): output must match _hash_raw
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_ctx_api)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["raw_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);
    size_t failures = 0;

    for (size_t idx = 0; idx < vecs.size(); ++idx) {
        const UniValue& v        = vecs[idx];
        const std::string ts     = v["type"].get_str();
        const uint32_t t         = v["t_cost"].getInt<uint32_t>();
        const uint32_t m         = v["m_cost"].getInt<uint32_t>();
        const uint32_t p         = v["parallelism"].getInt<uint32_t>();
        const size_t hlen        = v["hash_len"].getInt<size_t>();
        auto data                = ParseHex(v["data"].get_str());
        auto salt                = ParseHex(v["salt"].get_str());
        const auto expected      = ParseHex(v["expected_hash"].get_str());
        const argon2_type type   = ParseArgon2Type(ts);

        auto run_ctx = [&](bool generic) -> bool {
            std::vector<uint8_t> out(hlen, 0);
            argon2_context ctx;
            std::memset(&ctx, 0, sizeof(ctx));
            ctx.out          = out.data();
            ctx.outlen       = static_cast<uint32_t>(hlen);
            ctx.pwd          = data.data();
            ctx.pwdlen       = static_cast<uint32_t>(data.size());
            ctx.salt         = salt.data();
            ctx.saltlen      = static_cast<uint32_t>(salt.size());
            ctx.secret       = nullptr;
            ctx.secretlen    = 0;
            ctx.ad           = nullptr;
            ctx.adlen        = 0;
            ctx.t_cost       = t;
            ctx.m_cost       = m;
            ctx.lanes        = p;
            ctx.threads      = p;
            ctx.version      = ARGON2_VERSION_NUMBER;
            ctx.allocate_cbk = nullptr;
            ctx.free_cbk     = nullptr;
            ctx.flags        = ARGON2_DEFAULT_FLAGS;

            int rc;
            if (generic) {
                rc = argon2_ctx(&ctx, type);
            } else {
                switch (type) {
                case Argon2_d:  rc = argon2d_ctx(&ctx);  break;
                case Argon2_i:  rc = argon2i_ctx(&ctx);  break;
                case Argon2_id: rc = argon2id_ctx(&ctx); break;
                default:        rc = ARGON2_INCORRECT_TYPE;
                }
            }
            BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                (generic ? "argon2_ctx" : "argon2[d/i/id]_ctx")
                << " rc=" << rc << " vec=" << idx);
            return out == expected;
        };

        // Typed ctx
        if (!run_ctx(false)) {
            ++failures;
            std::cerr << "CTX MISMATCH (typed) vec=" << idx << " type=" << ts << "\n";
        }
        // Generic ctx
        if (!run_ctx(true)) {
            ++failures;
            std::cerr << "CTX MISMATCH (generic) vec=" << idx << " type=" << ts << "\n";
        }
    }

    Argon2AutoDetect();
    BOOST_REQUIRE_EQUAL(failures, 0);
}

// ---------------------------------------------------------------------------
// Test 8 – argon2[d/i/id]_verify_ctx(): verify the low-level verify path
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_verify_ctx_api)
{
    const uint8_t pwd[]     = "hunter2";
    const uint8_t salt[]    = "saltsalt";   // 8 bytes
    const size_t  pwdlen    = sizeof(pwd)  - 1;
    const size_t  saltlen   = sizeof(salt) - 1;
    constexpr size_t hlen   = 32;

    const argon2_type types[] = {Argon2_d, Argon2_i, Argon2_id};

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (argon2_type type : types) {
        // Compute the reference hash via the convenience wrapper
        std::vector<uint8_t> ref_hash(hlen);
        int rc = TypedHashRaw(type, 1, 64, 1,
                               pwd, pwdlen, salt, saltlen,
                               ref_hash.data(), hlen);
        BOOST_REQUIRE_EQUAL(rc, ARGON2_OK);

        // Build a context pointing to a fresh output buffer (verify_ctx will
        // re-compute into ctx.out and compare against the 'hash' argument)
        std::vector<uint8_t> out_buf(hlen);
        std::vector<uint8_t> pwd_buf(pwd, pwd + pwdlen);
        std::vector<uint8_t> salt_buf(salt, salt + saltlen);

        argon2_context ctx;
        std::memset(&ctx, 0, sizeof(ctx));
        ctx.out       = out_buf.data();
        ctx.outlen    = static_cast<uint32_t>(hlen);
        ctx.pwd       = pwd_buf.data();
        ctx.pwdlen    = static_cast<uint32_t>(pwdlen);
        ctx.salt      = salt_buf.data();
        ctx.saltlen   = static_cast<uint32_t>(saltlen);
        ctx.t_cost    = 1;
        ctx.m_cost    = 64;
        ctx.lanes     = 1;
        ctx.threads   = 1;
        ctx.version   = ARGON2_VERSION_NUMBER;
        ctx.flags     = ARGON2_DEFAULT_FLAGS;

        // Correct hash → ARGON2_OK
        switch (type) {
        case Argon2_d:  rc = argon2d_verify_ctx(&ctx,  (const char*)ref_hash.data()); break;
        case Argon2_i:  rc = argon2i_verify_ctx(&ctx,  (const char*)ref_hash.data()); break;
        case Argon2_id: rc = argon2id_verify_ctx(&ctx, (const char*)ref_hash.data()); break;
        default:        rc = ARGON2_INCORRECT_TYPE;
        }
        BOOST_CHECK_MESSAGE(rc == ARGON2_OK,
            "verify_ctx should succeed for type=" << (int)type << " rc=" << rc);

        // Also test generic argon2_verify_ctx
        rc = argon2_verify_ctx(&ctx, (const char*)ref_hash.data(), type);
        BOOST_CHECK_MESSAGE(rc == ARGON2_OK,
            "argon2_verify_ctx (generic) should succeed for type=" << (int)type);

        // Corrupted hash → mismatch
        std::vector<uint8_t> bad_hash = ref_hash;
        bad_hash[0] ^= 0xFF;

        switch (type) {
        case Argon2_d:  rc = argon2d_verify_ctx(&ctx,  (const char*)bad_hash.data()); break;
        case Argon2_i:  rc = argon2i_verify_ctx(&ctx,  (const char*)bad_hash.data()); break;
        case Argon2_id: rc = argon2id_verify_ctx(&ctx, (const char*)bad_hash.data()); break;
        default:        rc = ARGON2_INCORRECT_TYPE;
        }
        BOOST_CHECK_NE(rc, ARGON2_OK);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 9 – argon2_encodedlen(): returned size must equal strlen(enc) + 1
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_encodedlen_utility)
{
    struct Case {
        argon2_type type;
        uint32_t t, m, p, saltlen, hashlen;
    };
    const Case cases[] = {
        {Argon2_d,  1,  64, 1,  8, 16},
        {Argon2_i,  2, 128, 1,  8, 32},
        {Argon2_id, 3, 256, 1, 16, 32},
        {Argon2_id, 1,  64, 4, 32, 32},
        {Argon2_i,  1,  64, 1, 64, 64},
        {Argon2_d,  1, 128, 2, 16, 32},
        {Argon2_id, 1,  64, 1,  8, 64},
    };

    const std::vector<uint8_t> pwd(16, 0xAB);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (const auto& c : cases) {
        const std::vector<uint8_t> salt(c.saltlen, 0xCD);
        size_t enc_len = argon2_encodedlen(c.t, c.m, c.p,
                                            c.saltlen, c.hashlen, c.type);
        BOOST_REQUIRE_GT(enc_len, 0);

        std::vector<char> buf(enc_len);
        int rc = TypedHashEncoded(c.type, c.t, c.m, c.p,
                                   pwd.data(), pwd.size(),
                                   salt.data(), salt.size(),
                                   c.hashlen, buf.data(), enc_len);
        BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
            "hash_encoded rc=" << rc << " for encodedlen case type=" << (int)c.type);

        // argon2_encodedlen must predict the exact buffer requirement
        // (string length + null terminator)
        size_t actual = std::strlen(buf.data()) + 1;
        BOOST_CHECK_MESSAGE(actual == enc_len,
            "encodedlen mismatch: predicted=" << enc_len
            << " actual=" << actual
            << " type=" << (int)c.type);
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 10 – argon2_error_message(): non-null, non-empty for every known code
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_error_message_api)
{
    // All error codes from the reference argon2 implementation
    const int codes[] = {
        ARGON2_OK,
        ARGON2_OUTPUT_PTR_NULL,
        ARGON2_OUTPUT_TOO_SHORT,
        ARGON2_OUTPUT_TOO_LONG,
        ARGON2_PWD_TOO_LONG,
        ARGON2_SALT_TOO_SHORT,
        ARGON2_SALT_TOO_LONG,
        ARGON2_AD_TOO_LONG,
        ARGON2_SECRET_TOO_LONG,
        ARGON2_TIME_TOO_SMALL,
        ARGON2_TIME_TOO_LARGE,
        ARGON2_MEMORY_TOO_LITTLE,
        ARGON2_MEMORY_TOO_MUCH,
        ARGON2_LANES_TOO_FEW,
        ARGON2_LANES_TOO_MANY,
        ARGON2_PWD_PTR_MISMATCH,
        ARGON2_SALT_PTR_MISMATCH,
        ARGON2_SECRET_PTR_MISMATCH,
        ARGON2_AD_PTR_MISMATCH,
        ARGON2_MEMORY_ALLOCATION_ERROR,
        ARGON2_FREE_MEMORY_CBK_NULL,
        ARGON2_ALLOCATE_MEMORY_CBK_NULL,
        ARGON2_INCORRECT_PARAMETER,
        ARGON2_INCORRECT_TYPE,
        ARGON2_OUT_PTR_MISMATCH,
        ARGON2_THREADS_TOO_FEW,
        ARGON2_THREADS_TOO_MANY,
        ARGON2_MISSING_ARGS,
        ARGON2_ENCODING_FAIL,
        ARGON2_DECODING_FAIL,
        ARGON2_THREAD_FAIL,
        ARGON2_DECODING_LENGTH_FAIL,
        ARGON2_VERIFY_MISMATCH,
    };

    for (int code : codes) {
        const char* msg = argon2_error_message(code);
        BOOST_CHECK_MESSAGE(msg != nullptr,
            "argon2_error_message returned nullptr for code=" << code);
        if (msg) {
            BOOST_CHECK_MESSAGE(std::strlen(msg) > 0,
                "argon2_error_message returned empty string for code=" << code);
        }
    }
}

// ---------------------------------------------------------------------------
// Test 11 – Invalid parameter handling: expected specific error codes
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_invalid_params)
{
    const uint8_t pwd[]  = "password";
    const size_t  pwdlen = sizeof(pwd) - 1;
    const uint8_t salt[] = "saltsalt";   // 8 bytes (minimum)
    const size_t  saltlen = sizeof(salt) - 1;
    uint8_t out[32] = {};
    char enc[256]   = {};

    // --- _hash_raw bad params ---

    // t_cost = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);

    // m_cost = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 0, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_MEMORY_TOO_LITTLE);

    // parallelism = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 0, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_LANES_TOO_FEW);

    // salt < 8 bytes
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 1, pwd, pwdlen, salt, saltlen - 1, out, 32),
        ARGON2_SALT_TOO_SHORT);

    // hash_len = 0
    BOOST_CHECK_EQUAL(
        argon2id_hash_raw(1, 64, 1, pwd, pwdlen, salt, saltlen, out, 0),
        ARGON2_OUTPUT_TOO_SHORT);

    // Same bad-param checks apply to the other two types
    BOOST_CHECK_EQUAL(
        argon2d_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);
    BOOST_CHECK_EQUAL(
        argon2i_hash_raw(0, 64, 1, pwd, pwdlen, salt, saltlen, out, 32),
        ARGON2_TIME_TOO_SMALL);

    // --- _hash_encoded bad params ---

    // Buffer too small → ARGON2_ENCODING_FAIL
    char tiny[4] = "";
    BOOST_CHECK_EQUAL(
        argon2id_hash_encoded(1, 64, 1, pwd, pwdlen, salt, saltlen, 32, tiny, sizeof(tiny)),
        ARGON2_ENCODING_FAIL);

    // --- _verify with garbage encoded string ---
    BOOST_CHECK_NE(argon2id_verify("not-a-valid-argon2-hash", pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2i_verify("not-a-valid-argon2-hash",  pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2d_verify("not-a-valid-argon2-hash",  pwd, pwdlen), ARGON2_OK);

    // --- _verify with correct format but wrong type prefix ---
    // Build a valid argon2id encoded string, then ask argon2i_verify to parse it
    size_t enc_len = argon2_encodedlen(1, 64, 1,
                                        static_cast<uint32_t>(saltlen), 32, Argon2_id);
    std::vector<char> enc_buf(enc_len);
    BOOST_REQUIRE_EQUAL(
        argon2id_hash_encoded(1, 64, 1, pwd, pwdlen, salt, saltlen, 32,
                               enc_buf.data(), enc_len),
        ARGON2_OK);
    // argon2i_verify must reject an argon2id-prefixed string
    BOOST_CHECK_NE(argon2i_verify(enc_buf.data(), pwd, pwdlen), ARGON2_OK);
    BOOST_CHECK_NE(argon2d_verify(enc_buf.data(), pwd, pwdlen), ARGON2_OK);

    (void)enc;  // suppress unused-variable warning
}

// ---------------------------------------------------------------------------
// Test 12 – Negative verify: corrupted data or hash must not pass
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_negative_verify)
{
    UniValue root = read_json(json_tests::argon2_api_test_vectors);
    const UniValue& vecs = root["encoded_vectors"];
    BOOST_REQUIRE(vecs.isArray());
    BOOST_REQUIRE_GT(vecs.size(), 0);

    Argon2AutoDetect(argon2_implementation::STANDARD);

    for (const std::string& ts : {"argon2d", "argon2i", "argon2id"}) {
        // Find the first vector matching this type
        for (size_t idx = 0; idx < vecs.size(); ++idx) {
            if (vecs[idx]["type"].get_str() != ts) continue;

            const auto data       = ParseHex(vecs[idx]["data"].get_str());
            const std::string enc = vecs[idx]["encoded"].get_str();
            const argon2_type type = ParseArgon2Type(ts);

            // Correct data → must verify
            BOOST_CHECK_MESSAGE(
                TypedVerify(type, enc.c_str(), data.data(), data.size()) == ARGON2_OK,
                "Expected OK for " << ts);

            // Flipped first byte of data → must not verify
            std::vector<uint8_t> corrupt = data;
            corrupt[0] ^= 0xFF;
            BOOST_CHECK_MESSAGE(
                TypedVerify(type, enc.c_str(), corrupt.data(), corrupt.size()) != ARGON2_OK,
                "Expected mismatch after data corruption for " << ts);

            // Truncated data (different length) → must not verify
            std::vector<uint8_t> truncated(data.begin(), data.begin() + (data.size() / 2));
            if (!truncated.empty()) {
                BOOST_CHECK_NE(
                    TypedVerify(type, enc.c_str(), truncated.data(), truncated.size()),
                    ARGON2_OK);
            }

            break; // one vector per type is sufficient for the negative test
        }
    }

    Argon2AutoDetect();
}

// ---------------------------------------------------------------------------
// Test 13 – ISA consistency: all compiled ISAs must agree for all three types
// ---------------------------------------------------------------------------
BOOST_AUTO_TEST_CASE(argon2_isa_consistency_all_types)
{
    // A handful of well-chosen inputs that cover different byte patterns.
    struct Input { const char* data_hex; const char* salt_hex; };
    const Input inputs[] = {
        {"cafebabe",         "0102030405060708"},
        {"deadbeef",         "fffefdfcfbfaf9f8"},
        {"000102030405060708090a0b0c0d0e0f", "aabbccddeeff00112233445566778899"},
        {"ffffffffffffffff",  "0000000000000000"},
        {"68656c6c6f",        "776f726c64303030"},   // "hello" / "world000"
    };
    constexpr uint32_t t = 1, m = 64, p = 1;
    constexpr size_t   hlen = 32;

    for (const auto& inp : inputs) {
        const auto data = ParseHex(inp.data_hex);
        const auto salt = ParseHex(inp.salt_hex);

        for (argon2_type type : {Argon2_d, Argon2_i, Argon2_id}) {
            // Compute the reference with STANDARD
            Argon2AutoDetect(argon2_implementation::STANDARD);
            std::vector<uint8_t> ref(hlen);
            int rc = TypedHashRaw(type, t, m, p,
                                   data.data(), data.size(),
                                   salt.data(), salt.size(),
                                   ref.data(), hlen);
            BOOST_REQUIRE_EQUAL(rc, ARGON2_OK);

            // Every other compiled ISA must produce the same result
            ForEachISA([&](argon2_implementation::UseImplementation impl,
                           const std::string& isa_name) {
                if (impl == argon2_implementation::STANDARD) return;
                Argon2AutoDetect(impl);
                std::vector<uint8_t> isa_out(hlen);
                rc = TypedHashRaw(type, t, m, p,
                                   data.data(), data.size(),
                                   salt.data(), salt.size(),
                                   isa_out.data(), hlen);
                BOOST_REQUIRE_MESSAGE(rc == ARGON2_OK,
                    isa_name << " failed for type=" << (int)type);
                BOOST_CHECK_MESSAGE(isa_out == ref,
                    isa_name << " differs from STANDARD for type="
                             << (int)type << " data=" << inp.data_hex);
            });
        }
    }

    Argon2AutoDetect();
}

BOOST_AUTO_TEST_SUITE_END()
