#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitweb network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x66,0xdd,
};

static const uint8_t chainparams_seed_signet[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x95,0xbd,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x47,0x9d,
};

static const uint8_t chainparams_seed_testnet4[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0xbc,0xcd,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
